/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CU7ug9qDKHi
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Caudex } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client";

import Link from "next/link";
import {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuLink,
} from "@/components/ui/navigation-menu";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

// IMAGES
import Image from "next/image";
import mugnaBackground from "../images/mugnabg.png";
import product from "../images/product.jpg";
import {
  FacebookImage,
  InstagramImage,
  LocationImage,
  TiktokImage,
} from "./image-index";

import { motion } from "framer-motion";

export function MainComponent() {
  const scrollToSection = (sectionId: string) => {
    const section = document.getElementById(sectionId);
    if (section) {
      window.scrollTo({
        top: section.offsetTop,
        behavior: "smooth",
      });
    }
  };

  const handleClick = (
    event: React.MouseEvent<HTMLAnchorElement, MouseEvent>,
    sectionId: string
  ) => {
    event.preventDefault(); // Prevents the default behavior of the button (e.g., form submission)
    scrollToSection(sectionId);
  };

  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="fixed top-0 left-0 right-0 z-10 w-full bg-white backdrop-blur px-4 lg:px-6 h-16 lg:h-[84px] flex items-center">
        <Link
          href="#"
          className="flex items-center justify-center"
          prefetch={false}
        >
          <Image
            src={mugnaBackground}
            alt="logo"
            className="p-4 w-24 h-24 lg:w-[200px] lg:h-[200px]"
          />
          <span className="sr-only">Mugna</span>
        </Link>
        <NavigationMenu className="ml-auto hidden lg:flex font-poppins">
          <NavigationMenuList>
            <NavigationMenuLink asChild>
              <Link
                href="#product"
                className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
                prefetch={false}
                onClick={(event) => handleClick(event, "product")}
              >
                Products
              </Link>
            </NavigationMenuLink>
            <NavigationMenuLink asChild>
              <Link
                href="#"
                className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
                prefetch={false}
                onClick={(event) => handleClick(event, "partner-store")}
              >
                Partner Stores
              </Link>
            </NavigationMenuLink>
            <NavigationMenuLink asChild>
              <Link
                href="#"
                className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
                prefetch={false}
                onClick={(event) => handleClick(event, "events")}
              >
                Events
              </Link>
            </NavigationMenuLink>
            <NavigationMenuLink asChild>
              <Link
                href="#"
                className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-accent/50 data-[state=open]:bg-accent/50"
                prefetch={false}
                onClick={(event) => handleClick(event, "contact-us")}
              >
                Contact us
              </Link>
            </NavigationMenuLink>
          </NavigationMenuList>
        </NavigationMenu>
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="outline" size="icon" className="ml-auto lg:hidden">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <div className="grid gap-2 py-6">
              <Link
                href="#product"
                className="flex w-full items-center py-2 text-lg font-semibold"
                prefetch={false}
                onClick={(event) => handleClick(event, "product")}
              >
                Products
              </Link>
              <Link
                href="#"
                className="flex w-full items-center py-2 text-lg font-semibold"
                prefetch={false}
                onClick={(event) => handleClick(event, "partner-store")}
              >
                Partner Stores
              </Link>
              <Link
                href="#"
                className="flex w-full items-center py-2 text-lg font-semibold"
                prefetch={false}
                onClick={(event) => handleClick(event, "events")}
              >
                Events
              </Link>
              <Link
                href="#"
                className="flex w-full items-center py-2 text-lg font-semibold"
                prefetch={false}
                onClick={(event) => handleClick(event, "contact-us")}
              >
                Contact us
              </Link>
            </div>
          </SheetContent>
        </Sheet>
      </header>
      <main className="flex-1 pt-16 lg:pt-5">
        <motion.section
          className="relative w-full py-12 md:py-24 lg:py-32 z-0"
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="relative z-10 flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Discover the Natural Beauty of Woven Art
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Discover our groundbreaking products crafted to transform
                    your shopping experience.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#product"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Explore Products
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Send an Order
                  </Link>
                </div>
                <hr />
                {/* THIS IS FOR THE SOCMED ACCOUNTS */}
                <div className="flex flex-row gap-6 justify-center lg:justify-start">
                  <a href="https://www.facebook.com/wearmugna">
                    <Image
                      src={FacebookImage}
                      alt="facebook"
                      className="rounded hover:scale-110 cursor-pointer h-7 w-7"
                    />
                  </a>
                  <a href="https://www.instagram.com/mugnacebu/">
                    <Image
                      src={InstagramImage}
                      alt="instagram"
                      className="rounded hover:scale-110 cursor-pointer h-7 w-7"
                    />
                  </a>
                  <a href="https://www.tiktok.com/@mugnacebu">
                    <Image
                      src={TiktokImage}
                      alt="tiktok"
                      className="rounded hover:scale-110 cursor-pointer h-7 w-7"
                    />
                  </a>
                  <a href="https://maps.app.goo.gl/n9BGfMq9XJx1hEVW8">
                    <Image
                      src={LocationImage}
                      alt="location"
                      className="rounded hover:scale-110 cursor-pointer h-7 w-7"
                    />
                  </a>
                </div>
                <div></div>
              </div>
              <div className="relative z--1 flex justify-center">
                <Image
                  src={product}
                  width={300}
                  height={300}
                  alt="bg"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                />
              </div>
            </div>
          </div>
        </motion.section>
        <motion.section
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
          id="product"
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Featured Products
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Elevate Your Vacation Experience
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Discover our innovative products that redefine the way you
                  shop. From cutting-edge technology to stylish designs, we have
                  everything you need to elevate your retail experience.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="/placeholder.svg"
                  width="300"
                  height="300"
                  alt="Product"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Smart Checkout Kiosk</h3>
                  <p className="text-muted-foreground">
                    Streamline your checkout process with our cutting-edge
                    self-service kiosks.
                  </p>
                  <Link
                    href="#"
                    className="justify-start inline-flex h-9 items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Related Products
                  </Link>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="/placeholder.svg"
                  width="300"
                  height="300"
                  alt="Product"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">
                    Augmented Reality Mirror
                  </h3>
                  <p className="text-muted-foreground">
                    Visualize products in your space with our innovative AR
                    mirror technology.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="/placeholder.svg"
                  width="300"
                  height="300"
                  alt="Product"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">
                    Intelligent Inventory System
                  </h3>
                  <p className="text-muted-foreground">
                    Optimize your inventory with our AI-powered tracking and
                    management system.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </motion.section>
        <motion.section
          className="w-full py-12 md:py-24 lg:py-32"
          id="partner-store"
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                  Partner Stores
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Discover Our Retail Partners
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore our network of partner stores and find the perfect
                  location to experience our innovative products.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Partner"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Retail Emporium</h3>
                  <p className="text-muted-foreground">
                    Experience our products at our flagship store in the heart
                    of the city.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Visit Store
                  </Link>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="/placeholder.svg"
                  width="150"
                  height="150"
                  alt="Partner"
                  className="mx-auto aspect-square overflow-hidden rounded-xl object-contain"
                />
                <div className="space-y-2 text-center">
                  <h3 className="text-xl font-bold">Tech Emporium</h3>
                  <p className="text-muted-foreground">
                    Discover our latest innovations at our tech-focused partner
                    store.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Visit Store
                  </Link>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Image
                  src="/placeholder.svg"
                  width={500}
                  height={500}
                  alt="yeah"
                />
              </div>
            </div>
          </div>
        </motion.section>

        {/* THIS IS FOR THE EVENTS SECTION */}
        <motion.section
          className="w-full py-12 md:py-24 lg:py-32"
          id="events"
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <div className="container px-4 md:px-6"></div>
        </motion.section>

        {/* THIS IS FOR THE CONTACT SECTION */}

        <motion.section
          className="w-full py-12 md:py-24 lg:py-32"
          id="contact-us"
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <div className="container px-4 md:px-6"></div>
        </motion.section>
      </main>
    </div>
  );
}

function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
